//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deviceinfoSet
    {
        public int Id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string productor { get; set; }
        public string devicetype { get; set; }
        public int totallifetime { get; set; }
        public int usedlifetime { get; set; }
        public System.DateTime buildtime { get; set; }
        public int lineinfoSetId { get; set; }
    
        public virtual lineinfoSet lineinfoSet { get; set; }
        public virtual deviceworkinginfoSet deviceworkinginfoSet { get; set; }
    }
}
