//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deviceworkinginfoSet
    {
        public int Id { get; set; }
        public bool runningstatus { get; set; }
        public int mainspeed { get; set; }
        public int errorcount { get; set; }
        public int totalcount { get; set; }
        public System.DateTime buildtime { get; set; }
        public bool isruning { get; set; }
        public bool isfinished { get; set; }
        public bool iswarning { get; set; }
    
        public virtual deviceinfoSet deviceinfoSet { get; set; }
    }
}
