//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SRMSEntities : DbContext
    {
        public SRMSEntities()
            : base("name=SRMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<deviceinfoSet> deviceinfoSet { get; set; }
        public virtual DbSet<deviceworkinginfoSet> deviceworkinginfoSet { get; set; }
        public virtual DbSet<lineinfoSet> lineinfoSet { get; set; }
        public virtual DbSet<manipulatorinfoSet> manipulatorinfoSet { get; set; }
        public virtual DbSet<productinfoSet> productinfoSet { get; set; }
        public virtual DbSet<lineworkinfo> lineworkinfoSet { get; set; }
        public virtual DbSet<workdetail> workdetailSet { get; set; }
    }
}
